{
  "name":"Google", "description":"Google平台图标", 
  "icons":[    
    {"name":"Component1", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component1.png"},
    {"name":"Component2", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component2.png"},
    {"name":"Component3", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component3.png"},
    {"name":"Component4", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component4.png"},
    {"name":"Component5", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component5.png"},
    {"name":"Component6", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component6.png"},
    {"name":"Component7", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component7.png"},
    {"name":"Component8", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component8.png"},
    {"name":"Component9", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component9.png"},
    {"name":"Component10", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component10.png"},
    {"name":"Component11", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component11.png"},
    {"name":"Component12", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component12.png"},
    {"name":"Component13", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component13.png"},
    {"name":"Component14", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component14.png"},
    {"name":"Component15", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component15.png"},
    {"name":"Component16", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component16.png"},
    {"name":"Component17", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component17.png"},
    {"name":"Component18", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component18.png"},
    {"name":"Component19", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component19.png"},
    {"name":"Component20", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component20.png"},
    {"name":"Component21", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component21.png"},
    {"name":"Component22", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component22.png"},
    {"name":"Component23", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component23.png"},
    {"name":"Component24", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component24.png"},
    {"name":"Component25", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component25.png"},
    {"name":"Component26", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component26.png"},
    {"name":"Component27", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component27.png"},
    {"name":"Component28", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component28.png"},
    {"name":"Component29", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component29.png"},
    {"name":"Component30, "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/Component30.png"},
    {"name":"googlepayicon", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Google/googlepayicon.png"},

 ]
}
