{
  "name":"PlatformApp", "description":"其他一些平台图标", 
  "icons":[    
    {"name":"Amazon", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Amazon.png"},
    {"name":"AmazonBooks", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/AmazonBooks.png"},
    {"name":"AmazonMusic", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/AmazonMusic.png"},
    {"name":"Audible", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Audible.png"},
    {"name":"Deezer", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Deezer.png"},
    {"name":"DisneyPlus", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/DisneyPlus.png"},
    {"name":"ebay", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/ebay.png"},
    {"name":"EPIC", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/EPIC.png"},
    {"name":"Firefox", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Firefox.png"},
    {"name":"Hulu", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Hulu.png"},
    {"name":"Kindle", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Kindle.png"},
    {"name":"LINE", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/LINE.png"},
    {"name":"Max", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Max.png"},
    {"name":"Netflix", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Netflix.png"},
    {"name":"OneDrive", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/OneDrive.png"},
    {"name":"Opera", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Opera.png"},
    {"name":"Paramount", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Paramount.png"},
    {"name":"Playstation", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Playstation.png"},
    {"name":"Podcast", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Podcast.png"},
    {"name":"PrimeReading", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/PrimeReading.png"},
    {"name":"Primevideo", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Primevideo.png"},
    {"name":"SoundCloud", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/SoundCloud.png"},
    {"name":"Spotify", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Spotify.png"},
    {"name":"Star", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Star.png"},
    {"name":"Starz", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Starz.png"},
    {"name":"Steam", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Steam.png"},
    {"name":"Telegram", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Telegram.png"},
    {"name":"Tidal", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Tidal.png"},
    {"name":"Twitter", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Twitter.png"},
    {"name":"Vimeo", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Vimeo.png"},
    {"name":"Walmart", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Walmart.png"},
    {"name":"Walmart1", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/Walmart1.png"},
    {"name":"XBOX", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/XBOX.png"},
    {"name":"XBOX", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/XBOX1.png"},
    {"name":"YouTube", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/PlatformApp/YouTube.png"},
    {"name":"HSBC", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/HSBC.png"},
    {"name":"PayPay", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/PayPay.png"},
    {"name":"PayPay1", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/PayPay1.png"},
    {"name":"TNGWallet", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/TNGWallet.png"},
    {"name":"DBS", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/DBS.png"},
    {"name":"iFast", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/iFast.png"},
    {"name":"IBKR", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/IBKR.png"},
    {"name":"WISE", "url":"https://raw.githubusercontent.com/EliDoves/Proxy/refs/heads/main/Icon/Finance/WISE.png"},

 ]
}
